CREATE TABLE products (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    description varchar(500) NULL,
    price_amount numeric(18, 2) NOT NULL,
    price_currency varchar(3) NOT NULL CONSTRAINT df_products_price_currency DEFAULT 'USD',
    stock integer NOT NULL CONSTRAINT df_products_stock DEFAULT 0,
    owner_subject varchar(200) NOT NULL CONSTRAINT df_products_owner_subject DEFAULT 'legacy-owner',
    tenant_id varchar(100) NOT NULL CONSTRAINT df_products_tenant_id DEFAULT 'legacy-tenant',
    last_updated timestamptz NOT NULL CONSTRAINT df_products_last_updated DEFAULT now(),
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT ck_products_stock_non_negative CHECK (stock >= 0)
);

CREATE INDEX ix_products_tenant_id_owner_subject
    ON products (tenant_id, owner_subject);

CREATE TABLE customers (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    email varchar(320) NOT NULL,
    owner_subject varchar(200) NOT NULL CONSTRAINT df_customers_owner_subject DEFAULT 'legacy-owner',
    tenant_id varchar(100) NOT NULL CONSTRAINT df_customers_tenant_id DEFAULT 'legacy-tenant',
    date_created timestamptz NOT NULL CONSTRAINT df_customers_date_created DEFAULT now(),
    is_active boolean NOT NULL CONSTRAINT df_customers_is_active DEFAULT true,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_customers_tenant_id_owner_subject_email
    ON customers (tenant_id, owner_subject, email);

CREATE INDEX ix_customers_tenant_id_owner_subject
    ON customers (tenant_id, owner_subject);

CREATE TABLE orders (
    id uuid NOT NULL,
    customer_id integer NOT NULL,
    order_date timestamptz NOT NULL CONSTRAINT df_orders_order_date DEFAULT now(),
    status varchar(50) NOT NULL CONSTRAINT df_orders_status DEFAULT 'Pending',
    owner_subject varchar(200) NOT NULL CONSTRAINT df_orders_owner_subject DEFAULT 'legacy-owner',
    tenant_id varchar(100) NOT NULL CONSTRAINT df_orders_tenant_id DEFAULT 'legacy-tenant',
    last_updated timestamptz NOT NULL CONSTRAINT df_orders_last_updated DEFAULT now(),
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT fk_orders_customer_id FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE INDEX ix_orders_customer_id
    ON orders (customer_id);

CREATE INDEX ix_orders_status
    ON orders (status);

CREATE INDEX ix_orders_order_date
    ON orders (order_date DESC);

CREATE INDEX ix_orders_tenant_id_owner_subject
    ON orders (tenant_id, owner_subject);

CREATE INDEX ix_orders_tenant_id_owner_subject_customer_id
    ON orders (tenant_id, owner_subject, customer_id);

CREATE INDEX ix_orders_tenant_id_owner_subject_status
    ON orders (tenant_id, owner_subject, status);

CREATE TABLE order_items (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    order_id uuid NOT NULL,
    product_id integer NOT NULL,
    product_name varchar(100) NOT NULL,
    quantity integer NOT NULL,
    unit_price_excluding_gst numeric(18, 2) NOT NULL,
    currency varchar(3) NOT NULL CONSTRAINT df_order_items_currency DEFAULT 'USD',
    gst_rate numeric(5, 4) NOT NULL CONSTRAINT df_order_items_gst_rate DEFAULT 0.1000,
    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT fk_order_items_order_id FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product_id FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_order_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_order_items_unit_price_non_negative CHECK (unit_price_excluding_gst >= 0),
    CONSTRAINT ck_order_items_gst_rate_range CHECK (gst_rate >= 0 AND gst_rate <= 1)
);

CREATE INDEX ix_order_items_order_id
    ON order_items (order_id);

CREATE INDEX ix_order_items_product_id
    ON order_items (product_id);

CREATE TABLE outbox_messages (
    id uuid NOT NULL,
    occurred_on_utc timestamptz NOT NULL,
    type varchar(200) NOT NULL,
    correlation_id varchar(128) NOT NULL,
    payload text NOT NULL,
    processed_on_utc timestamptz NULL,
    retry_count integer NOT NULL CONSTRAINT df_outbox_messages_retry_count DEFAULT 0,
    error text NULL,
    processing_id uuid NULL,
    locked_until_utc timestamptz NULL,
    CONSTRAINT pk_outbox_messages PRIMARY KEY (id)
);

CREATE INDEX ix_outbox_messages_processed_on_utc_occurred_on_utc
    ON outbox_messages (processed_on_utc, occurred_on_utc);

CREATE INDEX ix_outbox_messages_unprocessed
    ON outbox_messages (processed_on_utc, occurred_on_utc)
    WHERE processed_on_utc IS NULL AND error IS NULL;

CREATE INDEX ix_outbox_messages_claimable
    ON outbox_messages (occurred_on_utc, locked_until_utc)
    WHERE processed_on_utc IS NULL AND error IS NULL;
