// Essential .NET namespaces
// Application libraries
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Net;
global using System.Net.Http;
global using System.Net.Http.Json;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Xml;
global using System.Xml.Linq;
global using Conventional;
global using Conventional.Conventions;
global using DbUp;
// Microsoft ASP.NET Core
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Routing;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata;
global using Microsoft.Extensions.DependencyInjection;
global using Npgsql;
// Logging with Serilog
global using Serilog;
global using Serilog.Events;
// Application references
global using StarterApp.Api.Application;
global using StarterApp.Api.Application.Commands;
global using StarterApp.Api.Application.DTOs;
global using StarterApp.Api.Application.Interfaces;
global using StarterApp.Api.Application.ReadModels;
global using StarterApp.Api.Data;
global using StarterApp.Api.Endpoints;
global using StarterApp.Api.Infrastructure;
global using StarterApp.Api.Infrastructure.Caching;
global using StarterApp.Api.Infrastructure.Identity;
global using StarterApp.Api.Infrastructure.Mediator;
global using StarterApp.Api.Infrastructure.Outbox;
global using StarterApp.Api.Infrastructure.Validation;
global using StarterApp.DbMigrator;
// Domain references
global using StarterApp.Domain.Abstractions;
global using StarterApp.Domain.Entities;
global using StarterApp.Domain.Enums;
global using StarterApp.Domain.Events;
global using StarterApp.Domain.ValueObjects;
global using StarterApp.Tests.Integration;
global using StarterApp.Tests.TestBuilders;
// Testing frameworks
global using Xunit;
global using Xunit.Abstractions;
